export const COMMISSION_DEFAULTS = {
  MODEL_TOKEN_VALUE_MIN: 0.065, // USD
  MODEL_TOKEN_VALUE_MAX: 0.08,  // USD
  DEFAULT_STUDIO_AGENCY_FEE_PCT: 0.20, // 20%
  PLATFORM_SYSTEM_FEE_FLAT: 50.00,
  TIERED_PAYOUT_ENABLED_DEFAULT: false,
};

export enum StudioFeeType {
  MEMBERSHIP = 'MEMBERSHIP_FIXED',
  HOURLY_SERVICE = 'SERVICE_HOURLY',
  SESSION_SERVICE = 'SERVICE_SESSION',
  PLATFORM_USAGE_PCT = 'PLATFORM_PCT',
  PENALTY = 'FINANCIAL_PENALTY'
}

public readonly TIMEZONE = 'America/Toronto'; // Standard timezone set by governance rules (WO-016-B).